import argparse, struct

def parse_args():
    parser = argparse.ArgumentParser()
    parser.add_argument(
        'original_platform',
        type=str,
        help='Location of `platform.bin` of ROM bundle in SDK or the one generated by `make_bundle.py`.')

    parser.add_argument(
        'app',
        type=str,
        help='Location of .bin of your app. This app uses its own RTOS implementation.')

    parser.add_argument(
        'output',
        type=str,
        help='Location to save the updated `platform.bin`.')

    return parser.parse_args()

if __name__ == '__main__':

    FLAGS = parse_args()

    BASE = 0x02002000

    with open(FLAGS.original_platform, 'rb') as f:
        original = f.read()

    with open(FLAGS.app, 'rb') as f:
        app = f.read()

    (sp,) = struct.unpack("<I", app[:4])
    print(f"ISR stack from APP => 0x{sp:08X}")

    app_addr = struct.unpack("<I", original[0xd0:0xd4])[0] - BASE

    original = bytearray(original)
    original[app_addr:app_addr + 4] = app[:4]

    with open(FLAGS.output, 'wb') as f:
        f.write(original)

    print(f"file saved to: {FLAGS.output}")
    print(f"Now use this file to replace the original `platform.bin` to make customized RTOS work.")
